const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";
const GET_FROM_CART_REQUEST = "GET_FROM_CART_REQUEST";
const GET_FROM_CART_SUCCESS = "GET_FROM_CART_SUCCESS";
const GET_FROM_CART_FAILURE = "GET_FROM_CART_FAILURE";
export const DELETE_FROM_CART_REQUEST="DELETE_FROM_CART_REQUEST"
export const DELETE_FROM_CART_SUCCESS="DELETE_FROM_CART_SUCCESS"
export const DELETE_FROM_CART_FAILURE="DELETE_FROM_CART_FAILURE"
export { ADD_TO_CART_REQUEST, ADD_TO_CART_SUCCESS, ADD_TO_CART_FAILURE,GET_FROM_CART_REQUEST,GET_FROM_CART_SUCCESS,GET_FROM_CART_FAILURE };