export const ADD_TO_WISHLIST_REQUEST = "ADD_TO_WISHLIST_REQUEST";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_FAILURE = "ADD_TO_WISHLIST_FAILURE";
export const GET_FROM_WISHLIST_REQUEST = "GET_FROM_WISHLIST_REQUEST";
export const GET_FROM_WISHLIST_SUCCESS = "GET_FROM_WISHLIST_SUCCESS";
export const GET_FROM_WISHLIST_FAILURE = "GET_FROM_WISHLIST_FAILURE";